
server:
  port: 8011
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/easypr?useUnicode=true&characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

